### ISSUE TITLE
Log file as command line option

### ISSUE THREAD

**Issue by andre2007** [d-language-server/dls#28]
While using dls from generic LSP plugin in IntelliJ it seems I do not have any possibility to set server options. At least the log file would be quite interesting. 
Could you add it as command line option?

**Comment by LaurentTreguier** [comment]
With 38b302fdc7b308e34bde7e03362460671547a30b, every initialization option will be available as a command line option

**Comment by andre2007** [comment]
Fantastic! 

One question, as far as I can see you already use LDC for the releases. That is great. Do you use also the command line switches to produce most optimized code?
I have a very big code base which even 32 bit dmd windows is unable to compile.

**Comment by LaurentTreguier** [comment]
The builds are made using dub's `releaseMode` and `optimize` options, which correspond to the `-release` and `-O3` flags for ldc.
I had left out inlining on purpose because I wondered if it was the cause of an issue (#20), but since it looks a lot like another issue that has been fixed (#25), I might add it back.

**Comment by andre2007** [comment]
Thanks for the info
