### ISSUE TITLE
Code completion items layout 

### ISSUE THREAD

**Issue by andre2007** [d-language-server/dls#29]
I am really unsure where to open this issue (DCD, Dls, IntelliJ LSP plugin,...) I assume maybe it fits here.

In the code completion list, the entries which are not selected you can read quite good, as the method name and the method signature have different colors. But the selected item, which is the one you also want to use is quite unreadable. There is some space missing between the method name and the method signature.
![image](https://user-images.githubusercontent.com/1451047/53169088-94616980-35dc-11e9-8e1c-07c6a826fe95.png)

**Comment by LaurentTreguier** [comment]
The completion identifiers and their documentation are sent in different fields, `label` and `documentation` respectively:
https://github.com/d-language-server/dls/blob/38b302fdc7b308e34bde7e03362460671547a30b/protocol/source/dls/protocol/interfaces/text_document.d#L184-L191
This is how it shows in VSCode:
![vscode-completion](https://user-images.githubusercontent.com/7602755/53170347-333b9500-35e0-11e9-9e66-334c75e4ada4.png)
So I think this is an issue with the way Intellij displays it. Whether the problem is with Inellij itself, or with intellij-lsp, I'm not sure however.

**Comment by andre2007** [comment]
Thanks a lot I created the lsp issue.
