### ISSUE TITLE
D language Project tester SEGFAULT

### ISSUE THREAD

**Issue by Basile-z** [d-language-server/dls#45]
I would like to bring your attention on https://buildkite.com/dlang/dmd/builds, DLS seems to fails since one or two days. It's not yet super visible because people does not always rebase their PR.

https://buildkite.com/dlang/dmd/builds/6674
https://buildkite.com/dlang/dmd/builds/6671
https://buildkite.com/dlang/dmd/builds/6666

**Comment by LaurentTreguier** [comment]
Once again, I can't manage to reproduce this on my machine... It seems to have no problem with the latest DMD master on my end.
I haven't been actively working on this as of late, so there have been very few changes recently. The last version was tagged 4 days ago, the previous one is from 18 days ago, and they are [only 3 commits between the two](https://github.com/d-language-server/dls/compare/v0.25.4...v0.25.5).
I've updated the `dub` and `containers` dependencies; and the two other commits don't really do much regarding memory management, nothing that should possibly lead to a segfault (as far as I can tell).

I'm thinking DLS should be pulled from the project tester, every time it breaks the CI it's not showing a compiler issue but only because of a weird circumstance, like having a `.editorconfig` in dlang/ci and such.

**Comment by Basile-z** [comment]
You confirm that you tested with DMD ~master ?

**Comment by LaurentTreguier** [comment]
Yes, this version to be exact:
```shell
$ dmd --version
DMD64 D Compiler v2.086.0-342-g6e78dd19f
```
(the host compiler used to compile it is DMD 2.086.0)

**Comment by Basile-z** [comment]
Thanks, so maybe it's nothing.
