### ISSUE TITLE
Sort results in code completion popup

### ISSUE THREAD

**Issue by RUSshy** [d-language-server/dls#51]
Hi,

Sometimes it is a pain to find what i'm looking for..

I think results should be sorted

VSCODE:
![image](https://user-images.githubusercontent.com/18348637/59127488-0f6e4600-8968-11e9-972b-ca29149b1509.png)

Jetbrains Rider:
![image](https://user-images.githubusercontent.com/18348637/59127502-1b5a0800-8968-11e9-9d8a-bfa6157f24d5.png)

Same class, same methods, you can already see wich one is much easier to read

**Comment by RUSshy** [comment]
I tried lot of different settings in vscode, but i couldn't find anything for that :(

**Comment by LaurentTreguier** [comment]
Apparently I had started sorting the completion results because every overload of the same symbol would appear as a separate entry, so you ended up with the same symbol name multiple times in the completion popup. I don't know if that was changed in later version of DCD, I'll go check it.
But even if this is still the case, if the symbol order is deterministic and the duplicate symbols are always adjacent, then sorting shouldn't be necessary to remove them.

**Comment by LaurentTreguier** [comment]
When I remove the sorting and duplicate removal, it looks like still only one instance of every symbol is shown. However, it's also still sorted alphabetically no matter what I do; so VSCode does this sorting by itself and I can't really change it.

**Comment by rwols** [comment]
Have you tried populating the `sortText` property of the completion items?

**Comment by LaurentTreguier** [comment]
I had completely forgotten about this ! I haven't really worked on DLS and with the LSP for some time, I remember having seen that property some months ago now. Setting this should indeed sort this out (pun half intended).
However, the actual order of what needs to appear first is yet to be decided; since I'm not doing much D right now, both of you might have a better insight on this.

Do you have an idea of an order to roughly choose what to display before other items ?

**Comment by rwols** [comment]
Somewhat off-topic, but also related to presenting completions:

> And really, something needs to be done for type info at the end of the line, it helps a LOT when looking for specific stuff, for all lines

Related: https://github.com/tomv564/LSP/issues/618
You might want to put the return type of functions in the `detail` field, and for variables put their type in the `detail` field.

> Do you have an idea of an order to roughly choose what to display before other items ?

I don't know, I don't write D :)

**Comment by LaurentTreguier** [comment]
> Related: [tomv564/LSP#618](https://github.com/tomv564/LSP/issues/618)
> You might want to put the return type of functions in the `detail` field, and for variables put their type in the `detail` field.

The problem with D is that because of its syntax, getting the return type of a function is not always as easy as I wish it was... Technically it could have an indefinite number of parens, meaning that regexes wouldn't be enough for this 😞

> I don't know, I don't write D :)

Ah I see, you're here because of the Sublime issue. I'll wait for @RUSshy's take on this

**Comment by RUSshy** [comment]
I'm not experienced D, but i'd personally make sure basic stuff is supported, the complex stuff can be supported later

I think jetbrains IDE are the best at UX:
![image](https://user-images.githubusercontent.com/18348637/59642156-3f85c800-9164-11e9-9d14-0a76247bbb17.png)

- fields
- functions
- callbacks
- keywords

**Comment by LaurentTreguier** [comment]
v0.25.13 will come up soon today. In addition to sorting according to symbol kinds, it also lowers the priority of certain members: `__monitor`, `__vptr` and `classinfo` are builtin properties that are rarely used I think, and members starting with an underscore are often private properties so they are automatically put after other properies.

**Comment by RUSshy** [comment]
Awesome, thanks a lot !!!!!! completion box is now much easier to read to find relevant information :)

Just now waiting for DCD to be released for that private field bug :)
